name: DAST Security Scan

on:
  # Menjalankan setelah workflow integration-tests selesai dijalankan
  workflow_run:
    workflows: ["Integration Tests"]
    types:
      - completed
  # Menjalankan secara manual jika diperlukan
  workflow_dispatch:

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    
    # Menambahkan izin khusus untuk job ini
    permissions:
      contents: read
      issues: write
      security-events: write
    
    steps:
    - name: Checkout kode
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl, pdo_mysql
    
    - name: Setup MySQL
      run: |
        sudo systemctl start mysql
        mysql -e "CREATE DATABASE IF NOT EXISTS damncrud;" -uroot -proot
        mysql -e "CREATE USER IF NOT EXISTS 'damncrud'@'localhost' IDENTIFIED BY 'damncrud123';" -uroot -proot
        mysql -e "GRANT ALL PRIVILEGES ON damncrud.* TO 'damncrud'@'localhost';" -uroot -proot
        mysql -uroot -proot damncrud < db/damncrud.sql
    
    - name: Setup Apache
      run: |
        sudo apt-get update
        sudo apt-get install apache2 libapache2-mod-php7.4
        sudo a2enmod php7.4
        sudo a2enmod rewrite
        sudo a2enmod headers
        sudo systemctl start apache2
        
        # Siapkan direktori di Apache
        sudo mkdir -p /var/www/html/DamnCRUD
        sudo cp -r $(pwd)/* /var/www/html/DamnCRUD/
        
        # Berikan izin yang benar
        sudo chown -R www-data:www-data /var/www/html/DamnCRUD
        sudo chmod -R 755 /var/www/html/DamnCRUD
        
        # Pastikan .htaccess aktif
        sudo sed -i '/<Directory \/var\/www\/>/,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf
        sudo systemctl reload apache2
        
        # Buat site config khusus
        echo -e "<VirtualHost *:80>\n\tServerName localhost\n\tDocumentRoot /var/www/html\n\t<Directory /var/www/html>\n\t\tOptions Indexes FollowSymLinks MultiViews\n\t\tAllowOverride All\n\t\tRequire all granted\n\t</Directory>\n</VirtualHost>" | sudo tee /etc/apache2/sites-available/000-default.conf
        sudo systemctl reload apache2
        
        # Periksa apakah Apache berfungsi dan folder dapat diakses
        ls -la /var/www/html/DamnCRUD/
        curl -I http://localhost/DamnCRUD/
    
    - name: Sesuaikan koneksi database
      run: |
        sudo sed -i 's/$DATABASE_HOST = .\+/$DATABASE_HOST = "localhost";/' /var/www/html/DamnCRUD/functions.php
        sudo sed -i 's/$DATABASE_USER = .\+/$DATABASE_USER = "damncrud";/' /var/www/html/DamnCRUD/functions.php
        sudo sed -i 's/$DATABASE_PASS = .\+/$DATABASE_PASS = "damncrud123";/' /var/www/html/DamnCRUD/functions.php
        sudo sed -i 's/$DATABASE_NAME = .\+/$DATABASE_NAME = "damncrud";/' /var/www/html/DamnCRUD/functions.php
    
    - name: Verifikasi aplikasi berjalan
      run: |
        # Verifikasi Apache berjalan
        sudo systemctl status apache2
        
        # Cek error log Apache
        sudo tail -n 50 /var/log/apache2/error.log
        
        # Cek akses ke halaman login
        curl -v http://localhost/DamnCRUD/login.php
      
    - name: OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost/DamnCRUD/'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'
    
    - name: OWASP ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.8.0
      with:
        target: 'http://localhost/DamnCRUD/'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'
    
    - name: Simpan laporan ZAP
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: zap-scan-reports
        path: |
          zap-*-report.html
          zap-*-report.md 